6

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -54,24 +54,44 @@ jobs:
     - name: Generate Pagefind search index
       run: npx pagefind --site "public"
     
-    - name: Debug Build Output  
-      run: ls -la ./public
+    - name: Check if ./public exists
+      run: |
+        if [ -d "./public" ]; then
+          echo "✅ The ./public directory exists!"
+          ls -la ./public
+        else
+          echo "❌ ERROR: The ./public directory does NOT exist!"
+          exit 1
+        fi
+   
 
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
       with:
-        path: ./public
+        path: ./public/**
+    - name: Verify Uploaded Artifacts
+      run: |
+        echo "Checking uploaded artifacts..."
+        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+             -H "Accept: application/vnd.github+json" \
+            https://api.github.com/repos/${{ github.repository }}/actions/artifacts
+
 
   # Deploy website to GitHub Pages hosting
   deploy:
     if: github.repository_owner != 'HugoBlox'
     environment:
       name: github-pages
-      url: https://pipelinesghubeus14.actions.githubusercontent.com/ifCvL7ej3tcCkvloCzQBJRAjsjnzjF7TteXnVOY4arLRO7zy1q/_apis/pipelines/workflows/13094737089/artifacts?api-version=6.0-preview
-      
+      url: ${{ steps.deployment.outputs.page_url }}
+     
+    
     runs-on: ubuntu-latest
     needs: build
     steps:
+    - name: List Available Artifacts
+      run: |
+        echo "Listing available artifacts..."
+        gh run artifacts
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v3
